version: "3.7"

services:
  app:
    # build:
    #   context: .
    image: polybean/hello-go:2.0
    environment:
      DB_HOST: db
      VERSION: 2.0
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mongo:4.0.11
    restart: always
