replica:
  app: 3
  db: 3
image:
  appTag: latest
  dbTag: 4.2.0
ingress:
  enabled: true
  host: polybean.io
service:
  # Change to NodePort if ingress.enable=false
  type: ClusterIP
rbac:
  enabled: true
resources:
  app:
    limits:
      cpu: 0.2
      memory: 20Mi
    requests:
      cpu: 0.1
      memory: 10Mi
  db:
    limits:
      memory: "200Mi"
      cpu: 0.2
    requests:
      memory: "100Mi"
      cpu: 0.1
dbPersistence:
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 2Gi
