kind: ConfigMap
apiVersion: v1
metadata:
  name: build-config
  namespace: build
data:
  build-config.properties: |
    project=hello-go
    image=polybean/hello-go
    domain=change.me
    cmSub=cm
    chartVer=0.0.1
