apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm.name" . }}
  labels:
    service: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replica.app }}
  selector:
    matchLabels:
      service: {{ template "helm.name" . }}-api
  template:
    metadata:
      labels:
        service: {{ template "helm.name" . }}-api
    spec:
      containers:
      - name: hello-go-api
        image: "polybean/hello-go:{{ .Values.image.tag }}"
        env:
        - name: DB_HOST
          value: {{ template "helm.name" . }}-db
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
{{ toYaml .Values.resources.app | indent 10 }}
