apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm.name" . }}-db
  labels:
    service: {{ template "helm.name" . }}-db
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    service: {{ template "helm.name" . }}-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm.name" . }}-api
  labels:
    service: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  ports:
  - port: 8080
  type: {{ .Values.service.type }}
  selector:
    service: {{ template "helm.name" . }}-api
